pub mod prompt;
pub mod skills;

use crate::environment::Environment;
use crate::error::{codes, err};
use crate::event_log::{events, hash_id, now_iso, EventLog, LogEntry};
use crate::role::{Backend, ModelSetting, SkillRef};
use crate::session::tmux::Tmux;
use crate::store::{DispatchRecord, RunRecord, Store};
use crate::worktree;
use anyhow::Result;
use std::fs;
use std::path::{Path, PathBuf};

pub struct LaunchSpec {
    pub run: RunRecord,
    pub role_label: String,
    pub is_core: bool,
    pub worktree: PathBuf,
    pub branch: String,
    pub backend: Backend,
    pub baseline: String,
    pub instructions: Vec<String>,
    pub task: String,
    pub skills: Vec<SkillRef>,
    pub model: ModelSetting,
    pub role_names_for_preamble: Vec<String>,
    pub created_fresh_worktree: bool,
    pub repo: PathBuf,
}

pub(crate) fn launch_script(backend: Backend) -> String {
    match backend {
        Backend::Claude => concat!(
            "#!/bin/sh\n",
            "# Generated by oat-agents. The agent's prompt is prompt.md beside this file.\n",
            "cd \"${OAT_WORKTREE:?}\" || exit 1\n",
            "exec \"${OAT_CLAUDE_COMMAND:-claude}\" --dangerously-skip-permissions \\\n",
            "  ${OAT_MODEL:+--model \"$OAT_MODEL\"} ${OAT_CLAUDE_ARGS:-} \\\n",
            "  \"$(cat \"${OAT_DISPATCH_DIR:?}/prompt.md\")\"\n",
        )
        .to_string(),
        Backend::Codex => concat!(
            "#!/bin/sh\n",
            "# Generated by oat-agents. The agent's prompt is prompt.md beside this file.\n",
            "cd \"${OAT_WORKTREE:?}\" || exit 1\n",
            "exec \"${OAT_CODEX_COMMAND:-codex}\" --full-auto \\\n",
            "  ${OAT_MODEL:+-m \"$OAT_MODEL\"} ${OAT_EFFORT:+-c model_reasoning_effort=\"$OAT_EFFORT\"} ${OAT_CODEX_ARGS:-} \\\n",
            "  \"$(cat \"${OAT_DISPATCH_DIR:?}/prompt.md\")\"\n",
        )
        .to_string(),
    }
}

pub(crate) const PASS_THROUGH_VARS: &[&str] = &[
    "OAT_AGENTS_LOG_DIR",
    "OAT_AGENTS_STATE_DIR",
    "OAT_AGENTS_CHECKLIST_DIR",
    "OAT_TMUX_COMMAND",
    "OAT_TMUX_SOCKET",
    "OAT_CLAUDE_COMMAND",
    "OAT_CODEX_COMMAND",
    "CLAUDE_CONFIG_DIR",
    "CODEX_HOME",
];

/// Materializes the Dispatch's skills, writes `prompt.md` and `launch.sh`, starts the tmux
/// session, and records the Dispatch. On a skill conflict, a worktree this call created is
/// removed so nothing is left half-prepared (ticket §6.2 rule 3).
pub fn launch_dispatch(
    env: &dyn Environment,
    store: &Store,
    log: &EventLog,
    spec: LaunchSpec,
    dispatch_id: String,
    model_env: (Option<String>, Option<String>),
) -> Result<(DispatchRecord, PathBuf)> {
    let tmux = Tmux::from_env(env);
    tmux.check_available()?;

    if let Err(e) = skills::materialize_skills(&spec.worktree, spec.backend, &spec.skills) {
        if spec.created_fresh_worktree {
            let _ = worktree::remove_worktree(
                &spec.repo,
                &spec.worktree,
                &spec.branch,
                &spec.run.base_branch,
                true,
            );
        }
        return Err(e);
    }

    let settle_command = if spec.is_core {
        "meta finish"
    } else {
        "dispatch done"
    };

    let preamble_template = if spec.is_core {
        prompt::PREAMBLE_CORE_ROLE
    } else {
        prompt::PREAMBLE_ROLE
    };

    let known_skills: std::collections::BTreeSet<String> =
        spec.skills.iter().map(|s| s.name.clone()).collect();

    let preamble = prompt::render_preamble(
        preamble_template,
        prompt::PreambleFields {
            role_name: &spec.role_label,
            run_id: &spec.run.id,
            dispatch_id: &dispatch_id,
            backend: spec.backend,
            worktree: &spec.worktree.to_string_lossy(),
            role_names: &spec.role_names_for_preamble,
            settle_command,
        },
        &known_skills,
    );

    let baseline_or_protocol = if spec.is_core {
        spec.baseline.as_str()
    } else {
        prompt::ROLE_PROTOCOL
    };

    let full_prompt = prompt::assemble(
        prompt::PromptParts {
            preamble,
            baseline: baseline_or_protocol,
            instructions: &spec.instructions,
            task: &spec.task,
        },
        spec.backend,
        &known_skills,
    );

    let dispatch_dir = store.dispatch_dir_path(&spec.run.id, &dispatch_id);
    fs::create_dir_all(&dispatch_dir)?;
    fs::write(dispatch_dir.join("prompt.md"), &full_prompt)?;
    let script = launch_script(spec.backend);
    let script_path = dispatch_dir.join("launch.sh");
    fs::write(&script_path, &script)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&script_path, fs::Permissions::from_mode(0o755))?;
    }

    let hid = hash_id(
        if spec.is_core { "meta" } else { &spec.role_label },
        &spec.run.name,
        &dispatch_id,
    );
    let session = Tmux::session_name(&hid);

    let (model, effort) = model_env;
    let mut env_vars = vec![
        ("OAT_RUN_ID".to_string(), spec.run.id.clone()),
        ("OAT_DISPATCH_ID".to_string(), dispatch_id.clone()),
        ("OAT_WORKTREE".to_string(), spec.worktree.to_string_lossy().to_string()),
        (
            "OAT_DISPATCH_DIR".to_string(),
            dispatch_dir.to_string_lossy().to_string(),
        ),
    ];
    if let Some(m) = model {
        env_vars.push(("OAT_MODEL".to_string(), m));
    }
    if let Some(e) = effort {
        env_vars.push(("OAT_EFFORT".to_string(), e));
    }
    for name in PASS_THROUGH_VARS {
        if let Some(v) = env.var(name) {
            env_vars.push((name.to_string(), v));
        }
    }

    tmux.start_session(
        &session,
        &spec.worktree,
        &env_vars,
        &script_path.to_string_lossy(),
    )?;

    let dispatch = DispatchRecord {
        id: dispatch_id.clone(),
        run_id: spec.run.id.clone(),
        role: spec.role_label.clone(),
        backend: format!("{:?}", spec.backend).to_lowercase(),
        worktree: spec.worktree.to_string_lossy().to_string(),
        branch: spec.branch.clone(),
        created_at: now_iso(),
        env_id: None,
        image_id: None,
        settled: None,
        report: None,
        released_at: None,
    };
    store.create_dispatch(&dispatch)?;

    log.record(&LogEntry {
        timestamp: now_iso(),
        run_id: spec.run.id.clone(),
        dispatch_id: Some(dispatch_id.clone()),
        agent: Some(spec.role_label.clone()),
        event: events::AGENT_ENTER.to_string(),
        details: Some(serde_json::json!({"worktree": dispatch.worktree, "backend": dispatch.backend})),
    })?;

    Ok((dispatch, dispatch_dir))
}

/// Claude Code workspace-trust handling (ticket §4.5): `--trust-workspace` records the
/// worktree as trusted in the user's `.claude.json`. A worktree that cannot take the write
/// still launches — this is hardening, not a prerequisite.
pub fn trust_claude_workspace(env: &dyn Environment, worktree: &Path) -> Result<()> {
    let Some(home) = env.home_dir() else {
        return Ok(());
    };
    let path = home.join(".claude.json");
    let mut root: serde_json::Value = fs::read_to_string(&path)
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or_else(|| serde_json::json!({}));
    if !root.is_object() {
        return Ok(());
    }
    let projects = root
        .as_object_mut()
        .unwrap()
        .entry("projects")
        .or_insert_with(|| serde_json::json!({}));
    if let Some(map) = projects.as_object_mut() {
        map.insert(
            worktree.to_string_lossy().to_string(),
            serde_json::json!({"hasTrustDialogAccepted": true}),
        );
    }
    fs::write(&path, serde_json::to_string_pretty(&root)?)?;
    Ok(())
}

/// Denies the `AskUserQuestion` tool inside the worktree, as hardening against a role trying
/// to ask a human through an interactive panel (ticket §4.5). A failure to write it is
/// hardening that did not apply, not a reason to fail the launch.
pub fn write_claude_local_settings(worktree: &Path) -> Result<()> {
    let dir = worktree.join(".claude");
    fs::create_dir_all(&dir)?;
    let path = dir.join("settings.local.json");
    let content = serde_json::json!({
        "permissions": {
            "deny": ["AskUserQuestion"]
        }
    });
    fs::write(&path, serde_json::to_string_pretty(&content)?)
        .map_err(|e| err(codes::INVALID_LOCAL_SETTINGS, e.to_string()))?;
    let _ = skills::append_local_exclude(worktree, ".claude/settings.local.json");
    Ok(())
}
