// SPDX-License-Identifier: MIT
// Copyright (c) 2026 oat-agents contributors

pub mod prompt;
pub mod skills;

use crate::environment::Environment;
use crate::error::{codes, err};
use crate::event_log::{events, hash_id, now_iso, EventLog, LogEntry};
use crate::role::{Backend, McpServer, ModelSetting, SkillRef};
use crate::session::tmux::Tmux;
use crate::store::{DispatchRecord, RunRecord, Store};
use crate::worktree;
use anyhow::Result;
use std::fs;
use std::path::{Path, PathBuf};

pub struct LaunchSpec {
    pub run: RunRecord,
    pub role_label: String,
    /// What the Dispatch is for, the last part of its hash_id; `None` names it after the Run.
    pub name: Option<String>,
    pub is_core: bool,
    pub worktree: PathBuf,
    pub branch: String,
    pub backend: Backend,
    pub baseline: String,
    pub instructions: Vec<String>,
    pub task: String,
    pub skills: Vec<SkillRef>,
    pub mcp_servers: Vec<McpServer>,
    pub model: ModelSetting,
    pub role_names_for_preamble: Vec<String>,
    pub created_fresh_worktree: bool,
    pub repo: PathBuf,
}

/// The script a session runs. Both backends start interactive, with the prompt as their
/// first turn: the session has to stay up after that turn for the live view to show it and
/// type at it — `codex exec` would answer once and exit, taking the pane with it.
pub(crate) fn launch_script(backend: Backend, mcp_servers: &[McpServer], dispatch_id: &str) -> String {
    let mcp_args = match backend {
        Backend::Claude if !mcp_servers.is_empty() => {
            "  --strict-mcp-config --mcp-config \"$OAT_DISPATCH_DIR/mcp-config.json\" \\\n".to_string()
        }
        Backend::Codex => codex_mcp_args(mcp_servers, dispatch_id),
        _ => String::new(),
    };
    let template = match backend {
        Backend::Claude => concat!(
            "#!/bin/sh\n",
            "# Generated by oat-agents. The agent's prompt is prompt.md beside this file.\n",
            "cd \"${OAT_WORKTREE:?}\" || exit 1\n",
            "exec \"${OAT_CLAUDE_COMMAND:-claude}\" --dangerously-skip-permissions \\\n",
            "  ${OAT_MODEL:+--model \"$OAT_MODEL\"} ${OAT_CLAUDE_ARGS:-} \\\n",
            "{{MCP_ARGS}}",
            "  \"$(cat \"${OAT_DISPATCH_DIR:?}/prompt.md\")\"\n",
        ),
        Backend::Codex => concat!(
            "#!/bin/sh\n",
            "# Generated by oat-agents. The agent's prompt is prompt.md beside this file.\n",
            "cd \"${OAT_WORKTREE:?}\" || exit 1\n",
            "exec \"${OAT_CODEX_COMMAND:-codex}\" --dangerously-bypass-approvals-and-sandbox \\\n",
            "  ${OAT_MODEL:+-m \"$OAT_MODEL\"} ${OAT_EFFORT:+-c model_reasoning_effort=\"$OAT_EFFORT\"} ${OAT_CODEX_ARGS:-} \\\n",
            "{{MCP_ARGS}}",
            "  \"$(cat \"${OAT_DISPATCH_DIR:?}/prompt.md\")\"\n",
        ),
    };
    template.replace("{{MCP_ARGS}}", &mcp_args)
}

fn runtime_mcp_name(server: &McpServer, dispatch_id: &str) -> String {
    let safe_dispatch = dispatch_id
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '-' || c == '_' { c } else { '_' })
        .collect::<String>();
    format!("oat_{safe_dispatch}_{}", server.name)
}

fn toml_inline_server(server: &McpServer) -> String {
    let mut fields = vec![format!("command = {}", toml::Value::String(server.command.clone()))];
    if !server.args.is_empty() {
        let args = server.args.iter().map(|arg| toml::Value::String(arg.clone()).to_string()).collect::<Vec<_>>();
        fields.push(format!("args = [{}]", args.join(", ")));
    }
    if !server.env.is_empty() {
        let env = server.env.iter().map(|(key, value)| format!("{key} = {}", toml::Value::String(value.clone()))).collect::<Vec<_>>();
        fields.push(format!("env = {{ {} }}", env.join(", ")));
    }
    format!("{{ {} }}", fields.join(", "))
}

pub(crate) fn sh_quote(argument: &str) -> String {
    format!("'{}'", argument.replace('\'', "'\\''"))
}

pub(crate) fn tmux_launch_command(script_path: &Path) -> String {
    format!("exec {}", sh_quote(&script_path.to_string_lossy()))
}

fn codex_mcp_args(servers: &[McpServer], dispatch_id: &str) -> String {
    let mut out = String::new();
    for server in servers {
        let name = runtime_mcp_name(server, dispatch_id);
        let setting = format!("mcp_servers.{name}={}", toml_inline_server(server));
        out.push_str("  -c ");
        out.push_str(&sh_quote(&setting));
        out.push_str(" \\\n");
    }
    out
}

#[derive(serde::Serialize)]
struct ClaudeMcpServer<'a> {
    command: &'a str,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    args: &'a Vec<String>,
    #[serde(skip_serializing_if = "std::collections::BTreeMap::is_empty")]
    env: &'a std::collections::BTreeMap<String, String>,
}

pub(crate) fn write_mcp_config(dispatch_dir: &Path, servers: &[McpServer], dispatch_id: &str) -> Result<()> {
    if servers.is_empty() {
        return Ok(());
    }
    let entries = servers.iter().map(|server| {
        (runtime_mcp_name(server, dispatch_id), ClaudeMcpServer {
            command: &server.command,
            args: &server.args,
            env: &server.env,
        })
    }).collect::<std::collections::BTreeMap<_, _>>();
    let path = dispatch_dir.join("mcp-config.json");
    fs::write(&path, serde_json::to_vec_pretty(&serde_json::json!({"mcpServers": entries}))?)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(path, fs::Permissions::from_mode(0o600))?;
    }
    Ok(())
}

pub(crate) const PASS_THROUGH_VARS: &[&str] = &[
    "OAT_AGENTS_LOG_DIR",
    "OAT_AGENTS_STATE_DIR",
    "OAT_AGENTS_CHECKLIST_DIR",
    "OAT_TMUX_COMMAND",
    "OAT_TMUX_SOCKET",
    "OAT_CLAUDE_COMMAND",
    "OAT_CODEX_COMMAND",
    "CLAUDE_CONFIG_DIR",
    "CODEX_HOME",
];

/// Materializes the Dispatch's skills, writes `prompt.md` and `launch.sh`, starts the tmux
/// session, and records the Dispatch. On a skill conflict, a worktree this call created is
/// removed so nothing is left half-prepared (ticket §6.2 rule 3).
pub fn launch_dispatch(
    env: &dyn Environment,
    store: &Store,
    log: &EventLog,
    spec: LaunchSpec,
    dispatch_id: String,
    model_env: (Option<String>, Option<String>),
) -> Result<(DispatchRecord, PathBuf)> {
    let tmux = Tmux::from_env(env);
    tmux.check_available()?;

    if let Err(e) = skills::materialize_skills(&spec.worktree, spec.backend, &spec.skills) {
        if spec.created_fresh_worktree {
            let _ = worktree::remove_worktree(
                &spec.repo,
                &spec.worktree,
                &spec.branch,
                &spec.run.base_branch,
                true,
            );
        }
        return Err(e);
    }

    let settle_command = if spec.is_core {
        "meta finish"
    } else {
        "dispatch done"
    };

    let preamble_template = if spec.is_core {
        prompt::PREAMBLE_CORE_ROLE
    } else {
        prompt::PREAMBLE_ROLE
    };

    let known_skills: std::collections::BTreeSet<String> =
        spec.skills.iter().map(|s| s.name.clone()).collect();

    let preamble = prompt::render_preamble(
        preamble_template,
        prompt::PreambleFields {
            role_name: &spec.role_label,
            run_id: &spec.run.id,
            dispatch_id: &dispatch_id,
            backend: spec.backend,
            worktree: &spec.worktree.to_string_lossy(),
            role_names: &spec.role_names_for_preamble,
            settle_command,
        },
        &known_skills,
    );

    let baseline_or_protocol = if spec.is_core {
        spec.baseline.as_str()
    } else {
        prompt::ROLE_PROTOCOL
    };

    let full_prompt = prompt::assemble(
        prompt::PromptParts {
            preamble,
            baseline: baseline_or_protocol,
            instructions: &spec.instructions,
            task: &spec.task,
        },
        spec.backend,
        &known_skills,
    );

    let dispatch_dir = store.dispatch_dir_path(&spec.run.id, &dispatch_id);
    fs::create_dir_all(&dispatch_dir)?;
    fs::write(dispatch_dir.join("prompt.md"), &full_prompt)?;
    write_mcp_config(&dispatch_dir, &spec.mcp_servers, &dispatch_id)?;
    let script = launch_script(spec.backend, &spec.mcp_servers, &dispatch_id);
    let script_path = dispatch_dir.join("launch.sh");
    fs::write(&script_path, &script)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(
            &script_path,
            fs::Permissions::from_mode(if spec.mcp_servers.is_empty() { 0o755 } else { 0o700 }),
        )?;
    }

    let hid = hash_id(
        if spec.is_core { "meta" } else { &spec.role_label },
        spec.name.as_deref().unwrap_or(&spec.run.name),
        &dispatch_id,
    );
    let session = Tmux::session_name(&hid);

    let (model, effort) = model_env;
    let mut env_vars = vec![
        ("OAT_RUN_ID".to_string(), spec.run.id.clone()),
        ("OAT_DISPATCH_ID".to_string(), dispatch_id.clone()),
        ("OAT_WORKTREE".to_string(), spec.worktree.to_string_lossy().to_string()),
        (
            "OAT_DISPATCH_DIR".to_string(),
            dispatch_dir.to_string_lossy().to_string(),
        ),
    ];
    if let Some(m) = &model {
        env_vars.push(("OAT_MODEL".to_string(), m.clone()));
    }
    if let Some(e) = &effort {
        env_vars.push(("OAT_EFFORT".to_string(), e.clone()));
    }
    for name in PASS_THROUGH_VARS {
        if let Some(v) = env.var(name) {
            env_vars.push((name.to_string(), v));
        }
    }

    let launch_command = tmux_launch_command(&script_path);
    tmux.start_session(
        &session,
        &spec.worktree,
        &env_vars,
        &launch_command,
    )?;

    let dispatch = DispatchRecord {
        id: dispatch_id.clone(),
        run_id: spec.run.id.clone(),
        role: spec.role_label.clone(),
        backend: format!("{:?}", spec.backend).to_lowercase(),
        worktree: spec.worktree.to_string_lossy().to_string(),
        branch: spec.branch.clone(),
        created_at: now_iso(),
        env_id: None,
        image_id: None,
        env_skipped: None,
        settled: None,
        report: None,
        released_at: None,
        name: spec.name.clone(),
        model,
        effort,
    };
    debug_assert_eq!(dispatch.hash_id(&spec.run), hid);
    store.create_dispatch(&dispatch)?;

    log.record(&LogEntry {
        timestamp: now_iso(),
        run_id: spec.run.id.clone(),
        dispatch_id: Some(dispatch_id.clone()),
        agent: Some(spec.role_label.clone()),
        event: events::AGENT_ENTER.to_string(),
        details: Some(serde_json::json!({"worktree": dispatch.worktree, "backend": dispatch.backend})),
    })?;

    Ok((dispatch, dispatch_dir))
}

/// Claude Code workspace-trust handling (ticket §4.5): `--trust-workspace` records the
/// worktree as trusted in the user's `.claude.json`. A worktree that cannot take the write
/// still launches — this is hardening, not a prerequisite.
pub fn trust_claude_workspace(env: &dyn Environment, worktree: &Path) -> Result<()> {
    let Some(home) = env.home_dir() else {
        return Ok(());
    };
    let path = home.join(".claude.json");
    let mut root: serde_json::Value = fs::read_to_string(&path)
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or_else(|| serde_json::json!({}));
    if !root.is_object() {
        return Ok(());
    }
    let projects = root
        .as_object_mut()
        .unwrap()
        .entry("projects")
        .or_insert_with(|| serde_json::json!({}));
    if let Some(map) = projects.as_object_mut() {
        map.insert(
            worktree.to_string_lossy().to_string(),
            serde_json::json!({"hasTrustDialogAccepted": true}),
        );
    }
    fs::write(&path, serde_json::to_string_pretty(&root)?)?;
    Ok(())
}

/// Denies the `AskUserQuestion` tool inside the worktree, as hardening against a role trying
/// to ask a human through an interactive panel (ticket §4.5). A failure to write it is
/// hardening that did not apply, not a reason to fail the launch.
pub fn write_claude_local_settings(worktree: &Path) -> Result<()> {
    let dir = worktree.join(".claude");
    fs::create_dir_all(&dir)?;
    let path = dir.join("settings.local.json");
    let content = serde_json::json!({
        "permissions": {
            "deny": ["AskUserQuestion"]
        }
    });
    fs::write(&path, serde_json::to_string_pretty(&content)?)
        .map_err(|e| err(codes::INVALID_LOCAL_SETTINGS, e.to_string()))?;
    let _ = skills::append_local_exclude(worktree, ".claude/settings.local.json");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn both_backends_start_interactive_so_the_session_outlives_its_first_turn() {
        let codex = launch_script(Backend::Codex, &[], "dispatch-test");
        assert!(codex.contains("codex}\" --dangerously-bypass-approvals-and-sandbox"), "{codex}");
        assert!(!codex.contains("\" exec "), "`codex exec` answers once and exits:\n{codex}");
        let claude = launch_script(Backend::Claude, &[], "dispatch-test");
        assert!(!claude.contains(" -p ") && !claude.contains("--print"), "{claude}");
    }

    #[cfg(unix)]
    #[test]
    fn codex_mcp_override_is_one_literal_argv_value_even_with_shell_metacharacters() {
        use std::os::unix::fs::PermissionsExt;
        use std::process::Command;

        let temp = tempfile::tempdir().unwrap();
        let worktree = temp.path().join("worktree space ' $(touch not-created)");
        let dispatch_dir = temp.path().join("dispatch space ' $(touch not-created)");
        fs::create_dir_all(&worktree).unwrap();
        fs::create_dir_all(&dispatch_dir).unwrap();
        let prompt = "A prompt with spaces ; $(touch not-created)";
        fs::write(dispatch_dir.join("prompt.md"), prompt).unwrap();

        let capture = temp.path().join("argv.json");
        let fake_cli = temp.path().join("fake codex ' command");
        fs::write(
            &fake_cli,
            "#!/usr/bin/env python3\nimport json, os, sys\nwith open(os.environ['CAPTURE'], 'w') as f: json.dump(sys.argv[1:], f)\n",
        )
        .unwrap();
        fs::set_permissions(&fake_cli, fs::Permissions::from_mode(0o755)).unwrap();

        let marker = temp.path().join("not-created");
        let marker_text = marker.to_string_lossy().to_string();
        let server = McpServer {
            name: "line".to_string(),
            command: format!("mcp; touch '{marker_text}'; echo 'quoted'"),
            args: vec!["space separated".to_string(), format!("$(touch '{marker_text}')")],
            env: std::collections::BTreeMap::from([(
                "VALUE".to_string(),
                format!("value ; $(touch '{marker_text}')"),
            )]),
        };
        let script_path = dispatch_dir.join("launch.sh");
        fs::write(&script_path, launch_script(Backend::Codex, std::slice::from_ref(&server), "dispatch-test"))
            .unwrap();
        fs::set_permissions(&script_path, fs::Permissions::from_mode(0o700)).unwrap();

        let output = Command::new("/bin/sh")
            .arg("-c")
            .arg(tmux_launch_command(&script_path))
            .env("OAT_WORKTREE", &worktree)
            .env("OAT_DISPATCH_DIR", &dispatch_dir)
            .env("OAT_CODEX_COMMAND", &fake_cli)
            .env("CAPTURE", &capture)
            .output()
            .unwrap();
        assert!(output.status.success(), "{}", String::from_utf8_lossy(&output.stderr));
        assert!(!marker.exists(), "shell metacharacters in plugin config and paths stay literal");

        let argv: Vec<String> = serde_json::from_slice(&fs::read(capture).unwrap()).unwrap();
        let config_index = argv.iter().position(|arg| arg == "-c").expect("Codex config override");
        let override_value = &argv[config_index + 1];
        let parsed: toml::Value = toml::from_str(override_value).expect("a syntactically valid Codex override");
        let config = parsed
            .get("mcp_servers")
            .and_then(|servers| servers.get("oat_dispatch-test_line"))
            .expect("per-dispatch server key");
        assert_eq!(config["command"].as_str(), Some(server.command.as_str()));
        assert_eq!(config["args"][0].as_str(), Some("space separated"));
        assert_eq!(config["args"][1].as_str(), Some(server.args[1].as_str()));
        assert_eq!(config["env"]["VALUE"].as_str(), Some(server.env["VALUE"].as_str()));
        assert_eq!(argv.last().map(String::as_str), Some(prompt));
    }

    #[cfg(unix)]
    #[test]
    fn claude_mcp_config_is_written_with_private_mode_and_strict_scoping() {
        use std::os::unix::fs::PermissionsExt;

        let temp = tempfile::tempdir().unwrap();
        let server = McpServer {
            name: "line".to_string(),
            command: "oat-line-mcp".to_string(),
            args: Vec::new(),
            env: std::collections::BTreeMap::new(),
        };
        let script = launch_script(Backend::Claude, std::slice::from_ref(&server), "dispatch-test");
        assert!(script.contains("--strict-mcp-config --mcp-config \"$OAT_DISPATCH_DIR/mcp-config.json\""));
        write_mcp_config(temp.path(), std::slice::from_ref(&server), "dispatch-test").unwrap();
        let path = temp.path().join("mcp-config.json");
        let config: serde_json::Value = serde_json::from_slice(&fs::read(&path).unwrap()).unwrap();
        assert_eq!(config["mcpServers"]["oat_dispatch-test_line"]["command"], "oat-line-mcp");
        assert_eq!(fs::metadata(path).unwrap().permissions().mode() & 0o777, 0o600);
    }
}
